### ISSUE TITLE
Separate rulesets from validateHtml function.

### ISSUE THREAD

**Issue by sparcut** [99xt/w3c-link-validator#45]
Enhancement for clarity when finding rulesets. As rule arrays get larger, it would be best to modulize or at least move them out of the `validateHtml` function.

Thus, making it similar to find ruleset one is looking for when reading code.

**Comment by shalithasuranga** [comment]
Yeah @sparcut  that's a very good idea. Please comment here if you are going to work with this issue.

@thinkholic , @rehrumesh  what's your idea regarding this

Thanks

**Comment by sparcut** [comment]
@shalithasuranga I'll work on this in a little bit. (in ~2 hours time)
