### ISSUE TITLE
Links to style guide

### ISSUE THREAD

**Issue by sparcut** [99xt/w3c-link-validator#46]
Enhancement for user.

Add link to google/other styleguide per rule so the user can find a greater explanation of a rule. Thus, if the user doesn't understand the problem from the short explanation, they can view style guide itself that usually has example etc.

This could also be added to show when verbosity is turned up, though would take up a lot of space.

**Comment by shalithasuranga** [comment]
Yeah good idea @sparcut 
We can add the official w3c reference link. We can implement it by adding new property to ruleset json.

What's your idea @thinkholic .

**Comment by shalithasuranga** [comment]
Closing due to long term inactivity
