### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by sparcut** [99xt/w3c-link-validator#47]
Would be great if there is a code style to follow. (eslint config?)

At the moment there is a mix, not sure which to follow.

E.g.

    if(xyz){
         console.log(xyz);
    }

or

    if (xyz) {
        console.log(xyz);
    }

etc.

**Comment by shalithasuranga** [comment]
Thanks for the issue @sparcut 
I prefer the second style. How about your idea @thinkholic

**Comment by sparcut** [comment]
@shalithasuranga What editor do you guy(s) use? 

[`.editorconfig`](http://editorconfig.org/) might be worth adding, easy way to make sure simple code styling is used. (most modern editors support or have extensions/packages to support) 

Otherwise, [`ESLint`](https://eslint.org/) allows for more style rules but takes a bit longer to initially setup config and setup in an editor.

**Comment by shalithasuranga** [comment]
Hi.. @sparcut .editorconfig requires plugin to be installed in editors. Thus  how about manually maintaining the style. I mean very first we can initially convert all to 4 spaces and 

```
if (xyz) {
    console.log(xyz);
}
```
style. Then all contributors will follow that style

Thanks

**Comment by shalithasuranga** [comment]
closing due to long term inactivity
