### ISSUE TITLE
Contributing docs

### ISSUE THREAD

**Issue by sparcut** [99xt/w3c-link-validator#51]
Add `CONTRIBUTING.md` to move current contribute info from `README.md` and add place for ruleset standards.

~~_Currently working on PR._~~ #52 :heavy_check_mark:

**Comment by shalithasuranga** [comment]
Hi.. @sparcut  you already created new `CONTRIBUTING.md` and linked with the `README.md` . How about "add place for ruleset standards."? Could you clearly mention your idea for improvement of existing docs.

Thanks

**Comment by sparcut** [comment]
@shalithasuranga Sorry, forgot to close this.
